
    name: CI - linux

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Linux dependencies
      shell: bash
      run: |
          # Azure repositories are not reliable, we need to prevent azure giving us packages. 
          # sudo rm -f /etc/apt/sources.list.d/*
          # sudo cp -f misc/ci/sources.list /etc/apt/sources.list
            sudo apt-get update
          # The actual dependencies
          sudo apt-get install build-essential pkg-config sudo libx11-dev libxcursor-dev \
          libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev \
          libdbus-1-dev libudev-dev libxi-dev libxrandr-dev yasm xvfb wget unzip \
          libopenal-dev libvorbis-dev libflac-dev xorg-dev
    - name: Install python  
      shell: bash
      run: |
            python -m pip install --upgrade pip      
    - name: Install dependencies with conan
      shell: bash
      run: |
            pip install conan
            cd cmake
            conan install ../scripts  
      env:
          CONAN_SYSREQUIRES_MODE: enabled
    - name: Build
      # Build your program with the given configuration    
      run: |
           mkdir build
           cd build
           cmake ..

        
